devspace quality-of-life commands

diff --git a/packages/grid/devspace.yaml b/packages/grid/devspace.yaml
--- a/packages/grid/devspace.yaml
+++ b/packages/grid/devspace.yaml
@@ -304,6 +304,8 @@ dev:
     imageSelector: "${DOCKER_IMAGE_SEAWEEDFS}:${SEAWEEDFS_VERSION}"
     ports:
       - port: "9333" # admin
+      - port: "8888" # filer
+      - port: "8333" # S3
   backend:
     imageSelector: "${CONTAINER_REGISTRY}/${DOCKER_IMAGE_BACKEND}"
     env:
@@ -323,6 +325,33 @@ profiles:
         path: deployments.seaweedfs-config
 
 commands:
+  reg-create:
+    command: |-
+      k3d registry create registry.localhost --port 12345 -v ~/.k3d-registry:/var/lib/registry
+      echo "Make sure to add the following to your /etc/hosts file:"
+      echo "127.0.0.1 k3d-registry.localhost"
+  reg-check:
+    command: |-
+      URL=http://k3d-registry.localhost:12345/v2/_catalog
+      echo "Checking registry connection to $URL"
+      curl -X GET $URL || (echo "ERROR: Registry URL is not reachable" && exit 1)
+  reg-delete:
+    command: |-
+      k3d registry delete registry.localhost
+  start:
+    command: |-
+      devspace run reg-check
+      k3d cluster create syft-dev -p "8080:80@loadbalancer" --registry-use k3d-registry.localhost:12345
+  deploy:
+    command: |-
+      devspace use context k3d-syft-dev
+      devspace use namespace syft
+      devspace --var CONTAINER_REGISTRY=k3d-registry.localhost:12345 deploy --config=devspace.yaml
   dev:
     command: |-
+      devspace use context k3d-syft-dev
+      devspace use namespace syft
       devspace --var CONTAINER_REGISTRY=k3d-registry.localhost:12345 dev --config=devspace.yaml
+  contexts:
+    command: |-
+      kubectl config get-contexts
