adding checks on the settings.yaml file

diff --git a/.github/workflows/pr-tests-syft.yml b/.github/workflows/pr-tests-syft.yml
--- a/.github/workflows/pr-tests-syft.yml
+++ b/.github/workflows/pr-tests-syft.yml
@@ -207,6 +207,29 @@ jobs:
             table_2_col_score: "${{ secrets.TEST_TABLE_2_COL_SCORE }}"
           EOF
 
+      # Check if the settings.yaml file is created
+      - name: Check settings.yaml existence
+        if: steps.changes.outputs.syft == 'true' || steps.changes.outputs.notebooks == 'true'
+        run: |
+          if [ ! -f ${GITHUB_WORKSPACE}/notebooks/scenarios/bigquery/settings.yaml ]; then
+            echo "Error: settings.yaml file not found!"
+            exit 1
+          fi
+          echo "settings.yaml file found."
+
+      # Verify the content of the settings.yaml file
+      - name: Validate settings.yaml content
+        if: steps.changes.outputs.syft == 'true' || steps.changes.outputs.notebooks == 'true'
+        run: |
+          required_keys=("gce_region" "gce_project_id" "gce_service_account" "external_registry" "dataset_1" "dataset_2" "table_1" "table_2" "table_2_col_id" "table_2_col_score")
+          for key in "${required_keys[@]}"; do
+            if ! grep -q "$key" ${GITHUB_WORKSPACE}/notebooks/scenarios/bigquery/settings.yaml; then
+              echo "Error: $key not found in settings.yaml!"
+              exit 1
+            fi
+          done
+          echo "All required keys are present in settings.yaml."
+
       - name: Run Bigquery Scenario Notebooks
         if: steps.changes.outputs.syft == 'true' || steps.changes.outputs.notebooks == 'true'
         run: |
