Adding pre-commit back in CI

diff --git a/.github/workflows/syft-pr_tests.yml b/.github/workflows/syft-pr_tests.yml
--- a/.github/workflows/syft-pr_tests.yml
+++ b/.github/workflows/syft-pr_tests.yml
@@ -22,96 +22,89 @@ defaults:
     working-directory: ./packages/syft
 
 jobs:
-  # python-linting:
-  #   runs-on: ubuntu-latest
-  #   strategy:
-  #     max-parallel: 1
-  #     matrix:
-  #       python-version: [3.9]
+  python-linting:
+    runs-on: ubuntu-latest
+    strategy:
+      max-parallel: 1
+      matrix:
+        python-version: [3.9]
 
-  #   steps:
-  #     - uses: actions/checkout@v2
+    steps:
+      - uses: actions/checkout@v2
 
-  #     - name: Set up Python ${{ matrix.python-version }}
-  #       uses: actions/setup-python@v2
-  #       with:
-  #         python-version: ${{ matrix.python-version }}
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
 
-  #     - name: Upgrade pip
-  #       run: |
-  #         pip install --upgrade --user pip
+      - name: Upgrade pip
+        run: |
+          pip install --upgrade --user pip
+      - name: Get pip cache dir
+        id: pip-cache
+        run: |
+          echo "::set-output name=dir::$(pip cache dir)"
+      - name: pip cache
+        uses: actions/cache@v2
+        with:
+          path: ${{ steps.pip-cache.outputs.dir }}
+          key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-py${{ matrix.python-version }}-
+      - name: Install Protoc
+        uses: arduino/setup-protoc@v1
+        with:
+          version: "3.x"
 
-  #     - name: Get pip cache dir
-  #       id: pip-cache
-  #       run: |
-  #         echo "::set-output name=dir::$(pip cache dir)"
+      - name: Build Protos
+        run: |
+          set -e
+          pip install black isort --default-timeout=60
+          ./scripts/build_proto.sh
+      # fails for no reason and breaks CI
+      # - id: file_changes # get changed files.
+      #   uses: trilom/file-changes-action@v1.2.3
+      #   with:
+      #     output: " "
+      - name: Hack pre-commit # https://github.com/pre-commit/action/issues/44
+        run: |
+          pwd
+          ls
+          cp .pre-commit-config.yaml ../../
+      - uses: pre-commit/action@v2.0.3
 
-  #     - name: pip cache
-  #       uses: actions/cache@v2
-  #       with:
-  #         path: ${{ steps.pip-cache.outputs.dir }}
-  #         key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-pip-py${{ matrix.python-version }}-
+       # - name: Run darglint via flake8 - Ignore Errors
+       #   continue-on-error: true
+       #   run: |
+       #     pip install darglint flake8
+       #     flake8 src tests
 
-  #     - name: Install Protoc
-  #       uses: arduino/setup-protoc@v1
-  #       with:
-  #         version: "3.x"
+       # check docstring coverage. If head coverage < base, exitcode = 1
+       # - uses: actions/checkout@v2
+       #   with:
+       #     fetch-depth: 0
 
-  #     - name: Build Protos
-  #       run: |
-  #         set -e
-  #         pip install black isort --default-timeout=60
-  #         ./scripts/build_proto.sh
+       # - name: Install docstr-coverage
+       #   run: pip install docstr-coverage --default-timeout=60
 
-  #     # fails for no reason and breaks CI
-  #     # - id: file_changes # get changed files.
-  #     #   uses: trilom/file-changes-action@v1.2.3
-  #     #   with:
-  #     #     output: " "
-  #     - name: Hack pre-commit # https://github.com/pre-commit/action/issues/44
-  #       run: |
-  #         pwd
-  #         ls
-  #         cp .pre-commit-config.yaml ../../
-  #     - uses: pre-commit/action@v2.0.3
-  #       continue-on-error: true
-  #     # with:
-  #     #   extra_args: --files ${{ steps.file_changes.outputs.files}} # apply only to changed files.
+       # - name: Get base coverage
+       #   run: |
+       #     git checkout ${{ github.event.pull_request.base.sha }}
+       #     echo "BASE_COV=$(docstr-coverage -p src)" >> $GITHUB_ENV
 
-  #     # - name: Run darglint via flake8 - Ignore Errors
-  #     #   continue-on-error: true
-  #     #   run: |
-  #     #     pip install darglint flake8
-  #     #     flake8 src tests
+       # - name: Get head coverage
+       #   continue-on-error: true
+       #   run: |
+       #     git checkout ${{ github.event.pull_request.head.sha }}
+       #     docstr-coverage -p --fail-under=$BASE_COV src
 
-  #     # check docstring coverage. If head coverage < base, exitcode = 1
-  #     # - uses: actions/checkout@v2
-  #     #   with:
-  #     #     fetch-depth: 0
-
-  #     # - name: Install docstr-coverage
-  #     #   run: pip install docstr-coverage --default-timeout=60
-
-  #     # - name: Get base coverage
-  #     #   run: |
-  #     #     git checkout ${{ github.event.pull_request.base.sha }}
-  #     #     echo "BASE_COV=$(docstr-coverage -p src)" >> $GITHUB_ENV
-
-  #     # - name: Get head coverage
-  #     #   continue-on-error: true
-  #     #   run: |
-  #     #     git checkout ${{ github.event.pull_request.head.sha }}
-  #     #     docstr-coverage -p --fail-under=$BASE_COV src
-
-  #     # - name: Check docstring modified files
-  #     #   if: ${{ failure() }}
-  #     #   run: |
-  #     #     git diff --name-only $(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}) | xargs docstr-coverage --accept-empty
+       # - name: Check docstring modified files
+       #   if: ${{ failure() }}
+       #   run: |
+       #     git diff --name-only $(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}) | xargs docstr-coverage --accept-empty
 
   python-tests-latest-versions:
-    # needs: [python-linting]
+     needs: [python-linting]
     strategy:
       max-parallel: 3
       matrix:
